package dev.openfit.app.ui.theme

import androidx.compose.ui.graphics.Color

val LightPrimary = Color(0xFF3A5C46)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFBCEAC7)
val LightOnPrimaryContainer = Color(0xFF00210B)
val LightSecondary = Color(0xFF4D6355)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFCFE8D6)
val LightOnSecondaryContainer = Color(0xFF0A2014)
val LightBackground = Color(0xFFF6FBF4)
val LightOnBackground = Color(0xFF171D18)
val LightSurface = Color(0xFFF6FBF4)
val LightOnSurface = Color(0xFF171D18)
val LightSurfaceVariant = Color(0xFFDBE5DA)
val LightOnSurfaceVariant = Color(0xFF404940)
val LightOutline = Color(0xFF707970)
val LightError = Color(0xFFBA1A1A)

val DarkPrimary = Color(0xFFA1CEAB)
val DarkOnPrimary = Color(0xFF063716)
val DarkPrimaryContainer = Color(0xFF214E2D)
val DarkOnPrimaryContainer = Color(0xFFBCEAC7)
val DarkSecondary = Color(0xFFB3CCBB)
val DarkOnSecondary = Color(0xFF1F3528)
val DarkSecondaryContainer = Color(0xFF354B3D)
val DarkOnSecondaryContainer = Color(0xFFCFE8D6)
val DarkBackground = Color(0xFF0F1510)
val DarkOnBackground = Color(0xFFDEE5DB)
val DarkSurface = Color(0xFF0F1510)
val DarkOnSurface = Color(0xFFDEE5DB)
val DarkSurfaceVariant = Color(0xFF404940)
val DarkOnSurfaceVariant = Color(0xFFBFD2BC)
val DarkOutline = Color(0xFF89928A)
val DarkError = Color(0xFFFFB4AB)
